FROM ritclizup/rit-ruby-builder
#You need to run docker build with Dockerfile.build first and pass the image name to this FROM
RUN apk add --no-cache curl bash sudo

RUN curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash