name: Push to Dockerhub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./python3-pyinstaller/
          push: true
          tags: python3-pyinstaller:latest
