name: Push to Dockerhub

on:    
  pull_request:
    paths: 
      - 'python3-pyinstaller/**'
    types: [closed]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            builder:
            - './python3-pyinstaller/Dockerfile.build'
            runner:
            - './python3-pyinstaller/Dockerfile'

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
            
      - name: Build and push Docker image
        if: steps.changes.outputs.src == 'runner'
        uses: docker/build-push-action@v2
        with:
          file: ./python3-pyinstaller/Dockerfile
          push: true
          tags: maurineimirandazup/python3-pyinstaller-runner:latest

      - name: Build and push Docker image
        if: steps.changes.outputs.builder == 'true'
        uses: docker/build-push-action@v2
        with:
          file: ./python3-pyinstaller/Dockerfile.build
          push: true
          tags: maurineimirandazup/python3-pyinstaller-builder:latest
