name: Push to Dockerhub

on:    
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v7.1
        id: verify-changed-files
        with:
          files: |
            ./python3-pyinstaller/Dockerfile
            ./python3-pyinstaller/Dockerfile.build
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
            
      - name: Build and push Docker image
        if: contains(steps.verify-changed-files.outputs.changed_files, 'Dockerfile')
        uses: docker/build-push-action@v2
        with:
          file: ./python3-pyinstaller/Dockerfile
          push: true
          tags: maurineimirandazup/python3-pyinstaller-runner:latest

      - name: Build and push Docker image
        if: contains(steps.verify-changed-files.outputs.changed_files, 'Dockerfile.build')
        uses: docker/build-push-action@v2
        with:
          file: ./python3-pyinstaller/Dockerfile.build
          push: true
          tags: maurineimirandazup/python3-pyinstaller-builder:latest
